    emailHost = "pop.gmail.com";
    emailProtocol = "pop3s";
    emailPort = 995;
    proxyUsername = "";
    proxyHost = ""
    proxyPort = "80"
    proxyPassword = ""
    recipentsToFilterIn = "amtwmg@gmail.com"
    messageIdStoreLocation="../store/processedEmailStore.json"
    cutOffDate = "09/01/2024"
